### PR TITLE
Add support for NPM v7+ audit report format

### PR DESCRIPTION
**Pull request by mpreziuso**
This adds support for NPM v7+ format (https://github.com/cy6erskunk/npm-audit-reporter-teamcity/issues/542).
Support for the older format is kept.

### CODE REVIEW

**Comment by cy6erskunk** [comment]
Hi @mpreziuso! Thanks a lot for the PR, it looks very promising! I'll try to take a look and do some local testing during the weekend. Not sure why the the actions were not triggered - those workflows are pretty old, I believe I can simplify them a bit.

**Comment by mpreziuso** [comment]
No problem @cy6erskunk ! 🙂
One thing I've noticed in my fork is that you can no longer have secrets that start with "GITHUB" but the ci one does rely on a GITHUB_TOKEN secret being there.

**Comment by cy6erskunk** [comment]
Hey @mpreziuso, I've updated the workflow and it should work now: I hope that it is enough to reopen this PR (or rebase it and force-push).

**Comment by mpreziuso** [comment]
Hi @cy6erskunk, I've run `npm audit fix` and pushed it - it now needs approval from you 🤞🏻

**Comment by cy6erskunk** [comment]
@mpreziuso, PR looks great, I am intending to merge it, thanks for your contribution a lot!
Do you want to add yourself to the `contributors` in `packages.json`? Or I can do it later when preparing the next release.

**Comment by mpreziuso** [comment]
@cy6erskunk Great news!
Thank you for reviewing and thanks for this package, it really made our lives easier by integrating NPM audit into Teamcity.

**Pull request merged**
